### ISSUE TITLE
Doesn't work with Isomorphic rendering

### ISSUE THREAD

**Issue by mearns** [hejmsdz/use-hash-param#14]
I'm trying to use this for isomorphic rendering; where my server uses `ReactDOMServer.renderToString` to serve the HTML page with default params, and then the client script takes over and re-renders with param values from the hash.

Using this on the client-side works well, but running it on the server fails because it expects `window` to exist.

I have a PR coming shortly to address this. The solution I came up with is to leverage the provided default value when window is undefined (e.g., on the server), and then use the existing `useEffect` hook to update the value based on the hash value when the element gets mounted.

**Comment by hejmsdz** [comment]
Thanks for reporting it and for your pull request. I've just released the version [0.2.4](https://www.npmjs.com/package/use-hash-param), which contains your changes. It should be available shortly 😃
