### ISSUE TITLE
setHashParam is typed to only accept a string as a value, but it should be able to accept 'undefined'

### ISSUE THREAD

**Issue by dionjwa** [hejmsdz/use-hash-param#17]
<img width="651" alt="image" src="https://user-images.githubusercontent.com/260221/116002815-49728080-a5b0-11eb-965f-a8a0a4f5a89a.png">

This:
```
export default function useHashParam(
  key: string,
  defaultValue: string
): [string, (value: string) => void];

```
should be instead: 

```
export default function useHashParam(
  key: string,
  defaultValue: string | undefined
): [string, (value: string|undefined) => void];

```

**Comment by hejmsdz** [comment]
Hi,

Sorry for taking so long, I nearly forgot about the existence of this repository and only today found some time for maintenance. This should be resolved in the newly published version `0.3.0`.
If something's still not quite right, feel free to reopen the issue.
