### ISSUE TITLE
use HTML5 hitory api replaceState method

### ISSUE THREAD

**Issue by capaj** [hejmsdz/use-hash-param#26]
typically you don't want to push a new entry into history stack with changes in hash.
Currently that's how this library operates.

Ideally we could choose the mode, while having replaceState as default.

**Comment by hejmsdz** [comment]
Hi,

Sorry for taking so long, I nearly forgot about the existence of this repository and only today found some time for maintenance. The newly published version `0.3.0` uses the replaceState API by default and you can use the old mode by passing an extra parameter to the setter function: `setValue(newValue, { history: 'push' })`

**Comment by capaj** [comment]
No problem. Thanks for finding the time.
The new API looks solid😎

**Comment by hejmsdz** [comment]
Thanks for dropping by and taking the time to submit the issue! You made a very good point that I just overlooked (honestly I didn't expect anyone would actually use this package... and here it is today with 700+ downloads per week) 😄
